export const KRUXT_EVENT_TYPES = [
  "workout.logged",
  "pr.verified",
  "rank.updated",
  "challenge.joined",
  "challenge.left",
  "challenge.progress_updated",
  "membership.status_changed",
  "consumer.entitlement_updated",
  "pricing.experiment_created",
  "pricing.experiment_assignment_created",
  "pricing.experiment_conversion_recorded",
  "discount.campaign_created",
  "discount.redeemed",
  "platform.plan_updated",
  "platform.gym_subscription_updated",
  "platform.gym_invoice_updated",
  "platform.gym_payment_failed",
  "platform.operator_access_granted",
  "platform.operator_access_revoked",
  "platform.support_access_grant_approved",
  "platform.support_session_started",
  "platform.feature_override_updated",
  "platform.kpi_snapshot_upserted",
  "data.partner_export_approved",
  "data.partner_export_completed",
  "security.user_auth_event_logged",
  "security.trusted_device_updated",
  "addons.subscription_updated",
  "automation.run_succeeded",
  "automation.run_failed",
  "partner.app_installed",
  "partner.revenue_event_recognized",
  "data.aggregation_job_completed",
  "data.release_approval_updated",
  "class.waitlist_promoted",
  "integration.sync_failed",
  "integration.sync_succeeded",
  "consent.recorded",
  "policy.version_published",
  "privacy.request_submitted",
  "privacy.request_status_changed",
  "privacy.request_overdue",
  "privacy.user_anonymized",
  "privacy.export_ready",
  "privacy.export_failed",
  "privacy.delete_completed",
  "privacy.delete_failed",
  "security.event_outbox",
  "incident.created",
  "incident.status_changed",
  "incident.deadline_recomputed",
  "incident.escalation_triggered",
  "incident.notification_delivered",
  "incident.notification_failed",
  "gym.brand_settings_updated",
  "gym.feature_setting_updated",
  "invoice.delivery_job_queued",
  "support.ticket_created",
  "support.ticket_status_changed",
  "support.automation_run_approved",
  "support.automation_run_rejected",
  "gym.permission_updated",
  "staff.shift_created",
  "staff.time_entry_submitted",
  "crm.lead_created",
  "crm.lead_status_changed",
  "analytics.daily_snapshot_upserted"
] as const;

export type KruxtEventType = (typeof KRUXT_EVENT_TYPES)[number];

export interface KruxtEventEnvelope<TPayload = Record<string, unknown>> {
  id: string;
  type: KruxtEventType;
  actorUserId?: string;
  subjectUserId?: string;
  gymId?: string;
  occurredAt: string;
  payload: TPayload;
}
