-- Curated first-party exercise catalog seed.
-- We intentionally store neutral exercise names and taxonomy, not third-party descriptions.

with seed(name, slug, category, movement_pattern, equipment) as (
  values
    ('Run', 'run', 'conditioning', 'gait', 'bodyweight'),
    ('Treadmill Run', 'treadmill-run', 'conditioning', 'gait', 'treadmill'),
    ('Walking', 'walking', 'conditioning', 'gait', 'bodyweight'),
    ('Incline Walk', 'incline-walk', 'conditioning', 'gait', 'treadmill'),
    ('Air Bike', 'air-bike', 'conditioning', 'cardio', 'bike'),
    ('Assault Bike', 'assault-bike', 'conditioning', 'cardio', 'bike'),
    ('Echo Bike', 'echo-bike', 'conditioning', 'cardio', 'bike'),
    ('BikeErg', 'bike-erg', 'conditioning', 'cardio', 'erg'),
    ('Row Erg', 'row-erg', 'conditioning', 'cardio', 'erg'),
    ('SkiErg', 'ski-erg', 'conditioning', 'cardio', 'erg'),
    ('Jump Rope', 'jump-rope', 'conditioning', 'cardio', 'rope'),
    ('Double Unders', 'double-unders', 'conditioning', 'cardio', 'rope'),

    ('Back Squat', 'back-squat', 'strength', 'squat', 'barbell'),
    ('Front Squat', 'front-squat', 'strength', 'squat', 'barbell'),
    ('Overhead Squat', 'overhead-squat', 'strength', 'squat', 'barbell'),
    ('Zercher Squat', 'zercher-squat', 'strength', 'squat', 'barbell'),
    ('Goblet Squat', 'goblet-squat', 'strength', 'squat', 'kettlebell'),
    ('Hack Squat', 'hack-squat', 'strength', 'squat', 'machine'),
    ('Leg Press', 'leg-press', 'strength', 'squat', 'machine'),
    ('Leg Extension', 'leg-extension', 'strength', 'knee-extension', 'machine'),
    ('Leg Curl', 'leg-curl', 'strength', 'knee-flexion', 'machine'),
    ('Split Squat', 'split-squat', 'strength', 'single-leg', 'bodyweight'),
    ('Bulgarian Split Squat', 'bulgarian-split-squat', 'strength', 'single-leg', 'bodyweight'),
    ('Walking Lunge', 'walking-lunge', 'strength', 'single-leg', 'bodyweight'),
    ('Reverse Lunge', 'reverse-lunge', 'strength', 'single-leg', 'bodyweight'),
    ('Step Up', 'step-up', 'strength', 'single-leg', 'box'),
    ('Calf Raise', 'calf-raise', 'strength', 'ankle-extension', 'bodyweight'),
    ('Deadlift', 'deadlift', 'strength', 'hinge', 'barbell'),
    ('Romanian Deadlift', 'romanian-deadlift', 'strength', 'hinge', 'barbell'),
    ('Sumo Deadlift', 'sumo-deadlift', 'strength', 'hinge', 'barbell'),
    ('Trap Bar Deadlift', 'trap-bar-deadlift', 'strength', 'hinge', 'trap-bar'),
    ('Good Morning', 'good-morning', 'strength', 'hinge', 'barbell'),
    ('Hip Thrust', 'hip-thrust', 'strength', 'hinge', 'barbell'),
    ('Glute Bridge', 'glute-bridge', 'strength', 'hinge', 'bodyweight'),

    ('Bench Press', 'bench-press', 'strength', 'horizontal-push', 'barbell'),
    ('Incline Bench Press', 'incline-bench-press', 'strength', 'horizontal-push', 'barbell'),
    ('Decline Bench Press', 'decline-bench-press', 'strength', 'horizontal-push', 'barbell'),
    ('Dumbbell Bench Press', 'dumbbell-bench-press', 'strength', 'horizontal-push', 'dumbbells'),
    ('Incline Dumbbell Press', 'incline-dumbbell-press', 'strength', 'horizontal-push', 'dumbbells'),
    ('Push Up', 'push-up', 'bodyweight', 'horizontal-push', 'bodyweight'),
    ('Weighted Push Up', 'weighted-push-up', 'bodyweight', 'horizontal-push', 'bodyweight'),
    ('Dip', 'dip', 'bodyweight', 'vertical-push', 'bodyweight'),
    ('Overhead Press', 'overhead-press', 'strength', 'vertical-push', 'barbell'),
    ('Push Press', 'push-press', 'strength', 'vertical-push', 'barbell'),
    ('Dumbbell Shoulder Press', 'dumbbell-shoulder-press', 'strength', 'vertical-push', 'dumbbells'),
    ('Arnold Press', 'arnold-press', 'strength', 'vertical-push', 'dumbbells'),
    ('Lateral Raise', 'lateral-raise', 'strength', 'shoulder-abduction', 'dumbbells'),
    ('Front Raise', 'front-raise', 'strength', 'shoulder-flexion', 'dumbbells'),
    ('Cable Fly', 'cable-fly', 'strength', 'horizontal-push', 'cable'),
    ('Pec Deck Fly', 'pec-deck-fly', 'strength', 'horizontal-push', 'machine'),
    ('Close Grip Bench Press', 'close-grip-bench-press', 'strength', 'horizontal-push', 'barbell'),
    ('Skull Crusher', 'skull-crusher', 'strength', 'elbow-extension', 'barbell'),
    ('Triceps Pushdown', 'triceps-pushdown', 'strength', 'elbow-extension', 'cable'),
    ('Overhead Triceps Extension', 'overhead-triceps-extension', 'strength', 'elbow-extension', 'cable'),

    ('Pull Up', 'pull-up', 'bodyweight', 'vertical-pull', 'bodyweight'),
    ('Chin Up', 'chin-up', 'bodyweight', 'vertical-pull', 'bodyweight'),
    ('Lat Pulldown', 'lat-pulldown', 'strength', 'vertical-pull', 'cable'),
    ('Bent Over Row', 'bent-over-row', 'strength', 'horizontal-pull', 'barbell'),
    ('Pendlay Row', 'pendlay-row', 'strength', 'horizontal-pull', 'barbell'),
    ('Seated Cable Row', 'seated-cable-row', 'strength', 'horizontal-pull', 'cable'),
    ('Single Arm Dumbbell Row', 'single-arm-dumbbell-row', 'strength', 'horizontal-pull', 'dumbbells'),
    ('Chest Supported Row', 'chest-supported-row', 'strength', 'horizontal-pull', 'machine'),
    ('T-Bar Row', 't-bar-row', 'strength', 'horizontal-pull', 'barbell'),
    ('Face Pull', 'face-pull', 'strength', 'horizontal-pull', 'cable'),
    ('Rear Delt Fly', 'rear-delt-fly', 'strength', 'horizontal-pull', 'dumbbells'),
    ('Inverted Row', 'inverted-row', 'bodyweight', 'horizontal-pull', 'bodyweight'),
    ('Barbell Curl', 'barbell-curl', 'strength', 'elbow-flexion', 'barbell'),
    ('Dumbbell Curl', 'dumbbell-curl', 'strength', 'elbow-flexion', 'dumbbells'),
    ('Hammer Curl', 'hammer-curl', 'strength', 'elbow-flexion', 'dumbbells'),
    ('Preacher Curl', 'preacher-curl', 'strength', 'elbow-flexion', 'machine'),

    ('Power Clean', 'power-clean', 'olympic', 'power', 'barbell'),
    ('Hang Power Clean', 'hang-power-clean', 'olympic', 'power', 'barbell'),
    ('Squat Clean', 'squat-clean', 'olympic', 'power', 'barbell'),
    ('Clean and Jerk', 'clean-and-jerk', 'olympic', 'power', 'barbell'),
    ('Split Jerk', 'split-jerk', 'olympic', 'power', 'barbell'),
    ('Push Jerk', 'push-jerk', 'olympic', 'power', 'barbell'),
    ('Snatch', 'snatch', 'olympic', 'power', 'barbell'),
    ('Power Snatch', 'power-snatch', 'olympic', 'power', 'barbell'),
    ('Hang Snatch', 'hang-snatch', 'olympic', 'power', 'barbell'),
    ('High Pull', 'high-pull', 'olympic', 'power', 'barbell'),

    ('Kettlebell Swing', 'kettlebell-swing', 'functional', 'hinge', 'kettlebell'),
    ('Thruster', 'thruster', 'functional', 'full-body', 'barbell'),
    ('Devil Press', 'devil-press', 'functional', 'full-body', 'dumbbells'),
    ('Med Ball Slam', 'med-ball-slam', 'functional', 'full-body', 'med-ball'),
    ('Battle Ropes', 'battle-ropes', 'functional', 'conditioning', 'ropes'),
    ('Box Jump', 'box-jump', 'functional', 'power', 'box'),
    ('Box Step Up', 'box-step-up', 'functional', 'single-leg', 'box'),
    ('Burpee', 'burpee', 'functional', 'full-body', 'bodyweight'),
    ('Burpee Over Bar', 'burpee-over-bar', 'functional', 'full-body', 'bodyweight'),
    ('Burpee Broad Jump', 'burpee-broad-jump', 'hyrox', 'full-body', 'bodyweight'),
    ('Wall Walk', 'wall-walk', 'functional', 'vertical-push', 'bodyweight'),
    ('Hand Release Push Up', 'hand-release-push-up', 'functional', 'horizontal-push', 'bodyweight'),
    ('Rope Climb', 'rope-climb', 'functional', 'vertical-pull', 'rope'),
    ('Toes to Bar', 'toes-to-bar', 'functional', 'core', 'bodyweight'),
    ('Wall Balls', 'wall-balls', 'hyrox', 'full-body', 'med-ball'),
    ('Sled Push', 'sled-push', 'hyrox', 'drive', 'sled'),
    ('Sled Pull', 'sled-pull', 'hyrox', 'pull', 'sled'),
    ('Sled Drag', 'sled-drag', 'functional', 'pull', 'sled'),
    ('Farmers Carry', 'farmers-carry', 'hyrox', 'carry', 'carry'),
    ('Suitcase Carry', 'suitcase-carry', 'functional', 'carry', 'carry'),
    ('Yoke Carry', 'yoke-carry', 'functional', 'carry', 'carry'),
    ('Sandbag Carry', 'sandbag-carry', 'functional', 'carry', 'sandbag'),
    ('Sandbag Lunges', 'sandbag-lunges', 'hyrox', 'single-leg', 'sandbag'),
    ('Tire Flip', 'tire-flip', 'functional', 'power', 'strongman'),

    ('Sit Up', 'sit-up', 'core', 'core', 'bodyweight'),
    ('V Up', 'v-up', 'core', 'core', 'bodyweight'),
    ('Hollow Hold', 'hollow-hold', 'core', 'core', 'bodyweight'),
    ('Plank', 'plank', 'core', 'core', 'bodyweight'),
    ('Side Plank', 'side-plank', 'core', 'core', 'bodyweight'),
    ('Russian Twist', 'russian-twist', 'core', 'core', 'bodyweight'),
    ('Hanging Knee Raise', 'hanging-knee-raise', 'core', 'core', 'bodyweight'),
    ('Leg Raise', 'leg-raise', 'core', 'core', 'bodyweight'),
    ('Ab Wheel Rollout', 'ab-wheel-rollout', 'core', 'core', 'ab-wheel'),
    ('Back Extension', 'back-extension', 'core', 'hinge', 'machine')
)
insert into public.exercises (
  name,
  slug,
  category,
  movement_pattern,
  equipment,
  is_public
)
select
  seed.name,
  seed.slug,
  seed.category,
  seed.movement_pattern,
  seed.equipment,
  true
from seed
on conflict (slug) do update
set
  name = excluded.name,
  category = excluded.category,
  movement_pattern = excluded.movement_pattern,
  equipment = excluded.equipment,
  is_public = true,
  updated_at = now();
