-- Expand the public exercise catalogue after the initial curated seed.
-- This supplements the existing catalogue with more bodybuilding,
-- calisthenics, hybrid, OCR, and machine-based movements.

with seed(name, slug, category, movement_pattern, equipment) as (
  values
    ('Machine Chest Press', 'machine-chest-press', 'strength', 'horizontal-push', 'machine'),
    ('Smith Machine Bench Press', 'smith-machine-bench-press', 'strength', 'horizontal-push', 'smith-machine'),
    ('Smith Machine Squat', 'smith-machine-squat', 'strength', 'squat', 'smith-machine'),
    ('Machine Shoulder Press', 'machine-shoulder-press', 'strength', 'vertical-push', 'machine'),
    ('Cable Lateral Raise', 'cable-lateral-raise', 'strength', 'shoulder-abduction', 'cable'),
    ('Reverse Pec Deck', 'reverse-pec-deck', 'strength', 'horizontal-pull', 'machine'),
    ('Machine Row', 'machine-row', 'strength', 'horizontal-pull', 'machine'),
    ('Machine Pullover', 'machine-pullover', 'strength', 'vertical-pull', 'machine'),
    ('Cable Curl', 'cable-curl', 'strength', 'elbow-flexion', 'cable'),
    ('Cable Hammer Curl', 'cable-hammer-curl', 'strength', 'elbow-flexion', 'cable'),
    ('Seated Leg Curl', 'seated-leg-curl', 'strength', 'knee-flexion', 'machine'),
    ('Lying Leg Curl', 'lying-leg-curl', 'strength', 'knee-flexion', 'machine'),
    ('Seated Calf Raise', 'seated-calf-raise', 'strength', 'ankle-extension', 'machine'),
    ('Standing Calf Raise', 'standing-calf-raise', 'strength', 'ankle-extension', 'machine'),
    ('Hip Abduction', 'hip-abduction', 'strength', 'hip-abduction', 'machine'),
    ('Hip Adduction', 'hip-adduction', 'strength', 'hip-adduction', 'machine'),
    ('Cable Kickback', 'cable-kickback', 'strength', 'hip-extension', 'cable'),
    ('Adductor Machine', 'adductor-machine', 'strength', 'hip-adduction', 'machine'),
    ('Abductor Machine', 'abductor-machine', 'strength', 'hip-abduction', 'machine'),

    ('Ring Dip', 'ring-dip', 'calisthenics', 'vertical-push', 'rings'),
    ('Ring Row', 'ring-row', 'calisthenics', 'horizontal-pull', 'rings'),
    ('Muscle Up', 'muscle-up', 'calisthenics', 'full-body', 'bodyweight'),
    ('Bar Muscle Up', 'bar-muscle-up', 'calisthenics', 'full-body', 'bar'),
    ('Ring Muscle Up', 'ring-muscle-up', 'calisthenics', 'full-body', 'rings'),
    ('Chest to Bar Pull Up', 'chest-to-bar-pull-up', 'calisthenics', 'vertical-pull', 'bar'),
    ('Strict Handstand Push Up', 'strict-handstand-push-up', 'calisthenics', 'vertical-push', 'bodyweight'),
    ('Kipping Handstand Push Up', 'kipping-handstand-push-up', 'calisthenics', 'vertical-push', 'bodyweight'),
    ('Pike Push Up', 'pike-push-up', 'calisthenics', 'vertical-push', 'bodyweight'),
    ('Pistol Squat', 'pistol-squat', 'calisthenics', 'single-leg', 'bodyweight'),
    ('Cossack Squat', 'cossack-squat', 'calisthenics', 'single-leg', 'bodyweight'),
    ('Nordic Curl', 'nordic-curl', 'calisthenics', 'knee-flexion', 'bodyweight'),
    ('Reverse Nordic Curl', 'reverse-nordic-curl', 'calisthenics', 'knee-extension', 'bodyweight'),
    ('L Sit', 'l-sit', 'calisthenics', 'core', 'bodyweight'),
    ('Front Lever Raise', 'front-lever-raise', 'calisthenics', 'core', 'bodyweight'),
    ('Back Lever Hold', 'back-lever-hold', 'calisthenics', 'core', 'bodyweight'),
    ('Skin the Cat', 'skin-the-cat', 'calisthenics', 'shoulder-mobility', 'rings'),
    ('Planche Lean', 'planche-lean', 'calisthenics', 'horizontal-push', 'bodyweight'),
    ('Human Flag Hold', 'human-flag-hold', 'calisthenics', 'core', 'bodyweight'),

    ('Shuttle Run', 'shuttle-run', 'conditioning', 'gait', 'bodyweight'),
    ('Hill Sprint', 'hill-sprint', 'conditioning', 'gait', 'bodyweight'),
    ('Stair Climb', 'stair-climb', 'conditioning', 'gait', 'stairs'),
    ('Weighted Vest Run', 'weighted-vest-run', 'conditioning', 'gait', 'weighted-vest'),
    ('Sled Sprint', 'sled-sprint', 'conditioning', 'drive', 'sled'),
    ('Prowler Push', 'prowler-push', 'conditioning', 'drive', 'sled'),
    ('Prowler Pull', 'prowler-pull', 'conditioning', 'pull', 'sled'),
    ('Row Sprint', 'row-sprint', 'conditioning', 'cardio', 'erg'),
    ('Ski Sprint', 'ski-sprint', 'conditioning', 'cardio', 'erg'),
    ('Bike Sprint', 'bike-sprint', 'conditioning', 'cardio', 'bike'),

    ('Bear Crawl', 'bear-crawl', 'functional', 'crawl', 'bodyweight'),
    ('Crab Walk', 'crab-walk', 'functional', 'crawl', 'bodyweight'),
    ('Walking Handstand', 'walking-handstand', 'functional', 'vertical-push', 'bodyweight'),
    ('Man Maker', 'man-maker', 'functional', 'full-body', 'dumbbells'),
    ('Sandbag Clean', 'sandbag-clean', 'functional', 'power', 'sandbag'),
    ('Sandbag to Shoulder', 'sandbag-to-shoulder', 'functional', 'power', 'sandbag'),
    ('Dumbbell Snatch', 'dumbbell-snatch', 'functional', 'power', 'dumbbells'),
    ('Kettlebell Snatch', 'kettlebell-snatch', 'functional', 'power', 'kettlebell'),
    ('Kettlebell Clean and Press', 'kettlebell-clean-and-press', 'functional', 'power', 'kettlebell'),
    ('Turkish Get Up', 'turkish-get-up', 'functional', 'stability', 'kettlebell'),
    ('Wall Sit', 'wall-sit', 'functional', 'isometric', 'bodyweight'),
    ('Dead Bug', 'dead-bug', 'core', 'core', 'bodyweight'),
    ('Bird Dog', 'bird-dog', 'core', 'core', 'bodyweight'),
    ('Pallof Press', 'pallof-press', 'core', 'anti-rotation', 'cable'),
    ('Cable Woodchop', 'cable-woodchop', 'core', 'rotation', 'cable'),

    ('Monkey Bars', 'monkey-bars', 'ocr', 'horizontal-pull', 'rig'),
    ('Rope Traverse', 'rope-traverse', 'ocr', 'horizontal-pull', 'rope'),
    ('Spear Throw', 'spear-throw', 'ocr', 'skill', 'spear'),
    ('Atlas Carry', 'atlas-carry', 'ocr', 'carry', 'stone'),
    ('Bucket Carry', 'bucket-carry', 'ocr', 'carry', 'bucket'),
    ('Hercules Hold', 'hercules-hold', 'ocr', 'grip', 'strongman'),
    ('Ape Hanger', 'ape-hanger', 'ocr', 'grip', 'rig'),
    ('Low Rig Traverse', 'low-rig-traverse', 'ocr', 'horizontal-pull', 'rig'),
    ('Wall Traverse', 'wall-traverse', 'ocr', 'climb', 'wall'),
    ('Cargo Net Climb', 'cargo-net-climb', 'ocr', 'climb', 'net'),
    ('Rope Climb No Legs', 'rope-climb-no-legs', 'ocr', 'vertical-pull', 'rope'),
    ('Sandbag Carry Uphill', 'sandbag-carry-uphill', 'ocr', 'carry', 'sandbag')
)
insert into public.exercises (
  name,
  slug,
  category,
  movement_pattern,
  equipment,
  is_public
)
select
  seed.name,
  seed.slug,
  seed.category,
  seed.movement_pattern,
  seed.equipment,
  true
from seed
on conflict (slug) do update
set
  name = excluded.name,
  category = excluded.category,
  movement_pattern = excluded.movement_pattern,
  equipment = excluded.equipment,
  is_public = true,
  updated_at = now();
