// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgomsmhsybrxjdxbgkjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhnb21zbWhzeWJyeGpkeGJna2p5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE1MTcwMjAsImV4cCI6MjA4NzA5MzAyMH0.yLWBfvr-TZ1LF-Lx_OPdhy_NhTKh08KdBPztayFSmV0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});